from __future__ import annotations

from pathlib import Path

from multimarket import dev045_d6r12_memory_attributed_real_diagnostic_contract as base

EXPERIMENT_ID = "DEV045-D6R13"
PREFLIGHT_ID = "DEV045-D6R13-REAL-DIAGNOSTIC-SUCCESSOR-PREFLIGHT-DESIGN-V1"
SCHEMA_VERSION = "dev045-d6r13-real-diagnostic-successor-preflight-design-v1"
STAGE_MODE = "PREFLIGHT_DESIGN_AND_SYNTHETIC_ONLY"

PARENT_FREEZE_HEAD = "4e27c8f9b9403bffcdc866e83ef7b3e79e03ee28"
D6R13_DESIGN_HEAD = "7a7e5f00501dec5f808a9b71ac350e3e6946f26f"
D6R13_DESIGN_FREEZE_MANIFEST_PATH = Path("evidence/dev045_d6r13_child_launch_successor_freeze.json")
D6R13_DESIGN_FREEZE_MANIFEST_SHA256 = "22700d1095af998d0f0ea279b4484e1f71392f0c7851aa997bdea8d961eadcfe"
D6R12_FAILURE_FREEZE_PATH = Path("evidence/dev045_d6r12_bounded_real_diagnostic_failure_freeze.json")
D6R12_FAILURE_FREEZE_SHA256 = "405fc0982f65d7982b5cf61939cf154bec65408aacdad9e548bebec629aa1c55"
D6R12_FAILURE_EVIDENCE_PATH = Path("evidence/dev045_d6r12_2026-02-01.json")
D6R12_FAILURE_EVIDENCE_SHA256 = "69c0cf784c39bcf75c7aea1a591ab10a808c8dd27855adb67d737f781226ccd1"
D6R12_RERUN_FORBIDDEN = True

DAY = base.DAY
SYMBOL = base.SYMBOL
EXCHANGE = base.EXCHANGE
SOURCE_PATH = base.SOURCE_PATH
SOURCE_ROWS = base.SOURCE_ROWS
SOURCE_BYTES = base.SOURCE_BYTES
SOURCE_SHA256 = base.SOURCE_SHA256
SOURCE_LINEAGE_EVIDENCE_PATH = Path("evidence/dev045_d6r9a_feb01_full_day_v2.json")
SOURCE_LINEAGE_EVIDENCE_SHA256 = "54afd16ca610b76de0658d68764b661335fcda23e3ae3ca4ce4de93c57c199d9"

HFTBACKTEST_VERSION = "2.4.4"
BOUNDED_WAKEUP_TARGET = base.BOUNDED_WAKEUP_TARGET
WAKEUP_CAPTURE_INTERVAL = base.WAKEUP_CAPTURE_INTERVAL
PREEXEC_MIN_MEMAVAILABLE_BYTES = base.PREEXEC_MIN_MEMAVAILABLE_BYTES
RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES = base.RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES
TOTAL_RSS_ABORT_THRESHOLD_BYTES = base.TOTAL_RSS_ABORT_THRESHOLD_BYTES
ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES = base.ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES
RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH = base.RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH

CHILD_MODULE_NAME = "multimarket.dev045_d6r13_child_launch_successor"
AUTHORIZATION_ENV = "DEV045_D6R13_AUTHORIZE"
AUTHORIZATION_TOKEN = "YES_FEB01_BOUNDED_MEMORY_DIAGNOSTIC_SUCCESSOR"
REAL_EXECUTION_ENABLED = False

RUNTIME_ROOT = Path("/home/emadh/Multi-Market/runtime/dev045_d6r13/2026-02-01")
ATTEMPT_MARKER_PATH = RUNTIME_ROOT / "ATTEMPT_STARTED.json"
MEMORY_HEARTBEAT_PATH = RUNTIME_ROOT / "MEMORY_HEARTBEAT.json"
EVIDENCE_PATH = Path("evidence/dev045_d6r13_2026-02-01.json")

MAX_SMALL_ARTIFACT_HASH_BYTES = 16 * 1024 * 1024
SOURCE_PREFLIGHT_ACCESS = "STAT_ONLY"
CANONICAL_DATA_OPEN_AUTHORIZED = False
HFTBACKTEST_CANONICAL_RUN_AUTHORIZED = False
ATTEMPT_MARKER_CREATION_AUTHORIZED = False
HEARTBEAT_CREATION_AUTHORIZED = False
FULL_DAY_ATTEMPT_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
POLICY_EXECUTION_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

PROHIBITED_EXECUTION_FLAGS = (
    REAL_EXECUTION_ENABLED,
    CANONICAL_DATA_OPEN_AUTHORIZED,
    HFTBACKTEST_CANONICAL_RUN_AUTHORIZED,
    ATTEMPT_MARKER_CREATION_AUTHORIZED,
    HEARTBEAT_CREATION_AUTHORIZED,
    FULL_DAY_ATTEMPT_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    POLICY_EXECUTION_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    CONVERTER_RERUN_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)

NEXT_STAGE = "DEV045-D6R13_REAL_DIAGNOSTIC_SUCCESSOR_EXECUTION_CODE_DESIGN"
