from __future__ import annotations

from pathlib import Path

from multimarket import dev045_d6r12_memory_attributed_real_diagnostic_contract as memory_design
from multimarket import dev045_d6r13_real_diagnostic_successor_preflight_contract as base

EXPERIMENT_ID = "DEV045-D6R13"
SCHEMA_VERSION = "dev045-d6r13-real-bounded-diagnostic-authorization-v1"
STAGE_MODE = "AUTHORIZED_NOT_EXECUTED"

PARENT_IMPLEMENTATION_FREEZE_HEAD = "83dc9f03c0965f4f627397ae7e3e072dbe1b0eb5"
IMPLEMENTATION_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r13_real_bounded_diagnostic_implementation_freeze.json"
)
PARENT_EXECUTION_CODE_FREEZE_HEAD = "76617a94af9350a1d969e7b07f7b7db44132ac40"
EXECUTION_CODE_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r13_real_diagnostic_execution_code_freeze.json"
)
PARENT_PREFLIGHT_FREEZE_HEAD = "1c29d6b59b9482a1bc37eafb2a03c339ce7449b9"
PREFLIGHT_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r13_real_diagnostic_successor_preflight_freeze.json"
)
D6R12_RERUN_FORBIDDEN = True
D6R12_DIAGNOSTIC_QUESTION_ANSWERED = False

DAY = base.DAY
SYMBOL = base.SYMBOL
EXCHANGE = base.EXCHANGE
SOURCE_PATH = base.SOURCE_PATH
SOURCE_ROWS = base.SOURCE_ROWS
SOURCE_BYTES = base.SOURCE_BYTES
SOURCE_SHA256 = base.SOURCE_SHA256
SOURCE_LINEAGE_EVIDENCE_PATH = base.SOURCE_LINEAGE_EVIDENCE_PATH
SOURCE_LINEAGE_EVIDENCE_SHA256 = base.SOURCE_LINEAGE_EVIDENCE_SHA256

HFTBACKTEST_VERSION = base.HFTBACKTEST_VERSION
BOUNDED_WAKEUP_TARGET = base.BOUNDED_WAKEUP_TARGET
WAKEUP_CAPTURE_INTERVAL = base.WAKEUP_CAPTURE_INTERVAL
PREEXEC_MIN_MEMAVAILABLE_BYTES = base.PREEXEC_MIN_MEMAVAILABLE_BYTES
RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES = base.RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES
TOTAL_RSS_ABORT_THRESHOLD_BYTES = base.TOTAL_RSS_ABORT_THRESHOLD_BYTES
ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES = base.ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES
RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH = base.RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH
OLD_D6R10_ABORT_BYTES = memory_design.OLD_D6R10_ABORT_BYTES
OLD_D6R10_LAST_HEARTBEAT_WAKEUPS = memory_design.OLD_D6R10_LAST_HEARTBEAT_WAKEUPS
BOUNDED_TARGET_TERMINAL_REASON = memory_design.BOUNDED_TARGET_TERMINAL_REASON
TARGET_OVERSHOOT_ERROR = memory_design.TARGET_OVERSHOOT_ERROR
LIFECYCLE_CAPTURE_POINTS = memory_design.LIFECYCLE_CAPTURE_POINTS
WAIT_NEXT_FEED_TIMEOUT_NS = 86_400_000_000_000
DIAGNOSTIC_TAIL_CHARS = 8192
MADV_SEQUENTIAL_IF_SUPPORTED = True

CHILD_MODULE_NAME = "multimarket.dev045_d6r13_real_diagnostic_execution"
CHILD_FLAG = "--child"
CHILD_RESOLUTION_SMOKE_FLAG = "--child-resolution-smoke"
PREFLIGHT_FLAG = "--preflight"

AUTHORIZATION_ENV = "DEV045_D6R13_AUTHORIZE"
AUTHORIZATION_TOKEN = "YES_FEB01_BOUNDED_MEMORY_DIAGNOSTIC_SUCCESSOR"
REAL_EXECUTION_ENABLED = True

RUNTIME_ROOT = Path("/home/emadh/Multi-Market/runtime/dev045_d6r13/2026-02-01")
ATTEMPT_MARKER_PATH = RUNTIME_ROOT / "ATTEMPT_STARTED.json"
MEMORY_HEARTBEAT_PATH = RUNTIME_ROOT / "MEMORY_HEARTBEAT.json"
EVIDENCE_PATH = Path("evidence/dev045_d6r13_2026-02-01.json")

CANONICAL_DATA_OPEN_AUTHORIZED = True
HFTBACKTEST_CANONICAL_RUN_AUTHORIZED = True
ATTEMPT_MARKER_CREATION_AUTHORIZED = True
HEARTBEAT_CREATION_AUTHORIZED = True
FULL_DAY_ATTEMPT_AUTHORIZED = False
FULL_DAY_VALIDATION_AUTHORIZED = False
MAR_TO_JUL_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
POLICY_EXECUTION_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
ORDER_CANCEL_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
RAW_CSV_OPEN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

AUTHORIZED_EXECUTION_FLAGS = (
    REAL_EXECUTION_ENABLED,
    CANONICAL_DATA_OPEN_AUTHORIZED,
    HFTBACKTEST_CANONICAL_RUN_AUTHORIZED,
    ATTEMPT_MARKER_CREATION_AUTHORIZED,
    HEARTBEAT_CREATION_AUTHORIZED,
)

PROHIBITED_EXECUTION_FLAGS = (
    FULL_DAY_ATTEMPT_AUTHORIZED,
    FULL_DAY_VALIDATION_AUTHORIZED,
    MAR_TO_JUL_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    POLICY_EXECUTION_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    ORDER_CANCEL_AUTHORIZED,
    CONVERTER_RERUN_AUTHORIZED,
    RAW_CSV_OPEN_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)

NEXT_STAGE = "DEV045-D6R13_FINAL_READONLY_LOCAL_PREFLIGHT"
