from __future__ import annotations

from pathlib import Path

from multimarket import dev045_d6r13_real_diagnostic_successor_preflight_contract as source
from multimarket import dev045_d6r14_memory_policy as memory_policy


EXPERIMENT_ID = "DEV045-D6R15"
SCHEMA_VERSION = "dev045-d6r15-full-day-successor-stack-v1"
STAGE_MODE = "AUTHORIZED_NOT_EXECUTED"

PARENT_D6R14_FREEZE_HEAD = "82123ef416b97a9caa239ea80da5a9d1887ed552"
PARENT_D6R14_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r14_memory_policy_feed_bound_freeze.json"
)
PARENT_D6R14_FREEZE_MANIFEST_SHA256 = (
    "63a1979e8c4ed61d2d28a9b17f5459ecdb1d8afd2abc78e56d79030625d9401b"
)

D6R12_RERUN_FORBIDDEN = True
D6R13_RERUN_FORBIDDEN = True
D6R13_ATTEMPT_CONSUMED = True
D6R13_DIAGNOSTIC_QUESTION_ANSWERED = True
ADDITIONAL_BOUNDED_MEMORY_DIAGNOSTIC_REQUIRED = False

DAY = source.DAY
SYMBOL = source.SYMBOL
EXCHANGE = source.EXCHANGE

SOURCE_PATH = source.SOURCE_PATH
SOURCE_ROWS = source.SOURCE_ROWS
SOURCE_BYTES = source.SOURCE_BYTES
SOURCE_SHA256 = source.SOURCE_SHA256

HFTBACKTEST_VERSION = source.HFTBACKTEST_VERSION

# D6R13 observed this by traversing the immutable Feb source to
# natural end-of-data.  It is a POST-EOD identity check only.
# It is NOT a stopping target.
REFERENCE_EOD_WAKEUPS = 7_139_910
REFERENCE_LAST_TIMESTAMP_NS = 1_769_990_399_913_791_000
FIXED_WAKEUP_STOP_TARGET = None

WAKEUP_CAPTURE_INTERVAL = 250_000
WAIT_NEXT_FEED_TIMEOUT_NS = 86_400_000_000_000
MADV_SEQUENTIAL_IF_SUPPORTED = True

TOTAL_RSS_ABORT_THRESHOLD_BYTES = (
    memory_policy.TOTAL_RSS_ABORT_THRESHOLD_BYTES
)
PREEXEC_MIN_MEMAVAILABLE_BYTES = (
    memory_policy.PREEXEC_MIN_MEMAVAILABLE_BYTES
)
RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES = (
    memory_policy.RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES
)
RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH = (
    memory_policy.RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH
)
ANONYMOUS_GROWTH_ABORT_THRESHOLD_BYTES = (
    memory_policy.ANONYMOUS_GROWTH_ABORT_THRESHOLD_BYTES
)
ANONYMOUS_GROWTH_BASELINE = (
    memory_policy.ANONYMOUS_GROWTH_BASELINE
)

NATURAL_END_OF_DATA_IS_VALID_TERMINAL = True
REFERENCE_EOD_VALIDATION_REQUIRED = True
REFERENCE_LAST_TIMESTAMP_VALIDATION_REQUIRED = True

CHILD_MODULE_NAME = "multimarket.dev045_d6r15_full_day_execution"
CHILD_FLAG = "--child"
CHILD_RESOLUTION_SMOKE_FLAG = "--child-resolution-smoke"
PREFLIGHT_FLAG = "--preflight"

AUTHORIZATION_ENV = "DEV045_D6R15_AUTHORIZE"
AUTHORIZATION_TOKEN = "YES_FEB01_FULL_DAY_FEED_ONLY_SUCCESSOR"

# The code is authorization-ready, but execution still requires the
# exact environment token. CI and this construction stage never set it.
REAL_EXECUTION_ENABLED = True

RUNTIME_ROOT = Path(
    "/home/emadh/Multi-Market/runtime/dev045_d6r15/2026-02-01"
)
ATTEMPT_MARKER_PATH = RUNTIME_ROOT / "ATTEMPT_STARTED.json"
MEMORY_HEARTBEAT_PATH = RUNTIME_ROOT / "MEMORY_HEARTBEAT.json"
EVIDENCE_PATH = Path("evidence/dev045_d6r15_2026-02-01.json")

CANONICAL_DATA_OPEN_AUTHORIZED = True
HFTBACKTEST_CANONICAL_RUN_AUTHORIZED = True
FULL_DAY_ATTEMPT_AUTHORIZED = True
FULL_DAY_VALIDATION_AUTHORIZED = True
ATTEMPT_MARKER_CREATION_AUTHORIZED = True
HEARTBEAT_CREATION_AUTHORIZED = True

MAR_TO_JUL_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
POLICY_EXECUTION_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
ORDER_CANCEL_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
RAW_CSV_OPEN_AUTHORIZED = False
CANONICAL_NPY_WRITE_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

AUTHORIZED_EXECUTION_FLAGS = (
    REAL_EXECUTION_ENABLED,
    CANONICAL_DATA_OPEN_AUTHORIZED,
    HFTBACKTEST_CANONICAL_RUN_AUTHORIZED,
    FULL_DAY_ATTEMPT_AUTHORIZED,
    FULL_DAY_VALIDATION_AUTHORIZED,
    ATTEMPT_MARKER_CREATION_AUTHORIZED,
    HEARTBEAT_CREATION_AUTHORIZED,
)

PROHIBITED_EXECUTION_FLAGS = (
    MAR_TO_JUL_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    POLICY_EXECUTION_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    ORDER_CANCEL_AUTHORIZED,
    CONVERTER_RERUN_AUTHORIZED,
    RAW_CSV_OPEN_AUTHORIZED,
    CANONICAL_NPY_WRITE_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)

NEXT_STAGE = "DEV045-D6R15_FINAL_READONLY_LOCAL_PREFLIGHT"
