from __future__ import annotations

from multimarket import (
    dev045_d6r26a_p2_r20_combined_day_context_midpoint_index_preexecution as r20,
)
from multimarket import (
    dev045_d6r26a_p2_r27p0_accelerated_context_engine_design_parity_freeze as r27p0,
)
from multimarket import (
    dev045_d6r26a_p2_r27p2_bounded_real_numba_benchmark_preexecution as r27p2,
)

EXPERIMENT_ID = "DEV045-D6R26A-P2-R27P3"
DESIGN_VERSION = "fused-full-context-kernel-architecture-freeze-v1"
PARENT_R27P2_HEAD = "9551f11604d02a897d4d749dd963f8d819cc8c80"

REFERENCE_IMPLEMENTATION = "R20_PYTHON_REFERENCE"
ACCELERATOR_FAMILY = "NUMBA_JIT"

# R27P2 proved the raw event classification/timestamp scan kernel has ample
# headroom. R27P3 now freezes the next architecture before implementation.
R27P2_REAL_KERNEL_GATE_PASSED = True
R27P2_GATE_PREFIX_ROWS = 5_000_000
R27P2_OBSERVED_GATE_SPEEDUP = 224.975
R27P2_MIN_REQUIRED_SPEEDUP = 10.0

# The successor must preserve the whole R20 semantic/output surface, not only
# the raw scan summary.
FULL_CONTEXT_ACCELERATOR_REQUIRED = True
EXACT_R20_OUTPUT_PARITY_REQUIRED = True
BOUNDS_PARITY_REQUIRED = True
FEATURE_SUMMARY_PARITY_REQUIRED = True
DECISION_ARRAY_PARITY_REQUIRED = True
BEST_BID_ARRAY_PARITY_REQUIRED = True
BEST_ASK_ARRAY_PARITY_REQUIRED = True
FEATURE_VALUES_PARITY_REQUIRED = True
MIDPOINT_RECORD_PARITY_REQUIRED = True
MIDPOINT_METADATA_PARITY_REQUIRED = True
RAW_EVENT_PASS_COUNT_PARITY_REQUIRED = True

# Architectural target: one causal raw-event pass with compiled state machines.
ONE_CAUSAL_RAW_EVENT_PASS_REQUIRED = True
PYTHON_PER_ROW_LOOP_FORBIDDEN_IN_ACCELERATED_REAL_PATH = True
PYTHON_BOOK_OBJECT_MATERIALIZATION_PER_GROUP_FORBIDDEN = True
PYTHON_FULL_BOOK_SORT_PER_GROUP_FORBIDDEN = True

# Preserve frozen raw-event semantics.
LOCAL_STREAM_SEMANTICS_FROZEN = True
EXCHANGE_STREAM_SEMANTICS_FROZEN = True
UNKNOWN_EVENT_FAIL_CLOSED = True
LOCAL_TIMESTAMP_REGRESSION_FAIL_CLOSED = True
EXCHANGE_TIMESTAMP_REGRESSION_FAIL_CLOSED = True
EVENT_SOURCE_ORDER_WITHIN_TIMESTAMP_GROUP_FROZEN = True
LOCAL_BOOK_BEFORE_SAME_TIMESTAMP_FLOWS_FROZEN = True
FINAL_TIMESTAMP_GROUP_FLUSH_REQUIRED = True
NATURAL_END_OF_SOURCE_SEMANTICS_FROZEN = True

# Preserve exact book semantics. Implementation may use compiled/vector state,
# but visible results must equal R9/R10/R20 exactly.
ABSOLUTE_DEPTH_UPDATE_SEMANTICS_FROZEN = True
CLEAR_SEMANTICS_FROZEN = True
SNAPSHOT_SEMANTICS_FROZEN = True
TRADE_DOES_NOT_MUTATE_L2_FROZEN = True
IGNORED_L2_EVENT_POLICY_FROZEN = True
BBO_VALIDITY_RULE_FROZEN = True
TOP5_DEPTH_SEMANTICS_FROZEN = True
CANDIDATE_VISIBLE_QTY_SEMANTICS_FROZEN = True

# Preserve rolling features exactly; no approximate time bucketing is allowed.
ROLLING_WINDOWS_EXACT_TIMESTAMP_BASED = True
APPROXIMATE_SECOND_BUCKETING_FORBIDDEN = True
FEATURE_WARMUP_SEMANTICS_FROZEN = True
RECENT_BOOK_ASOF_250MS_FROZEN = True
RECENT_BOOK_ASOF_1S_FROZEN = True
ROLLING_1S_5S_30S_BOUNDARIES_FROZEN = True
FLOAT64_FEATURE_OUTPUT_REQUIRED = True

# Preserve midpoint surface exactly.
MIDPOINT_RECORD_DTYPE_FROZEN = True
MIDPOINT_RECORD_BYTES = 16
MIDPOINT_EXCHANGE_TIMESTAMP_STRICTLY_INCREASING = True
MIDPOINT_LAST_BBO_PER_EXCHANGE_GROUP_FROZEN = True
MARKOUT_ASOF_RULE_FROZEN = True

# The accelerated implementation is allowed to change internal data structures
# only. Preferred form is compiled arrays / typed maps / bounded ring buffers.
INTERNAL_BOOK_REPRESENTATION_MAY_CHANGE = True
COMPILED_STATE_MACHINE_REQUIRED = True
BOUNDED_RING_BUFFERS_ALLOWED = True
TYPED_MAP_OR_VECTOR_BOOK_ALLOWED = True
DENSE_NUMPY_OUTPUT_SURFACE_REQUIRED = True
FILE_BACKED_MIDPOINT_OUTPUT_REQUIRED = True

# Development gates before any new full Jan-Jul materialization.
SYNTHETIC_EXACT_PARITY_GATE_REQUIRED = True
BOUNDED_REAL_FULL_CONTEXT_PARITY_GATE_REQUIRED = True
BOUNDED_REAL_FULL_CONTEXT_SPEED_GATE_REQUIRED = True
MIN_FULL_CONTEXT_SPEEDUP = 10.0
FULL_JAN_JUL_RERUN_REQUIRES_SEPARATE_SUCCESSOR_AUTHORIZATION = True

# Critical experiment safety.
P2_ATTEMPT_CONSUMED = False
HISTORICAL_SOURCE_OPEN_AUTHORIZED = False
HISTORICAL_SOURCE_REHASH_AUTHORIZED = False
FULL_JAN_JUL_RERUN_AUTHORIZED = False
DURABLE_CONTEXT_WRITE_AUTHORIZED = False
SIMULATOR_LANE_AUTHORIZED = False
ATTEMPT_MARKER_WRITE_AUTHORIZED = False
CANONICAL_LABEL_WRITE_AUTHORIZED = False
MODEL_FIT_AUTHORIZED = False
PNL_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False


class R27P3Error(RuntimeError):
    pass


def validate_r27p3_contract() -> None:
    r27p0.validate_r27p0_contract()
    r27p2.validate_r27p2_contract()
    r20.validate_r20_contract()

    if PARENT_R27P2_HEAD != "9551f11604d02a897d4d749dd963f8d819cc8c80":
        raise R27P3Error("parent")
    if REFERENCE_IMPLEMENTATION != "R20_PYTHON_REFERENCE":
        raise R27P3Error("reference")
    if ACCELERATOR_FAMILY != "NUMBA_JIT":
        raise R27P3Error("accelerator_family")
    if not R27P2_REAL_KERNEL_GATE_PASSED:
        raise R27P3Error("r27p2_gate")
    if R27P2_GATE_PREFIX_ROWS != 5_000_000:
        raise R27P3Error("r27p2_prefix")
    if R27P2_OBSERVED_GATE_SPEEDUP < R27P2_MIN_REQUIRED_SPEEDUP:
        raise R27P3Error("r27p2_speedup")
    if MIN_FULL_CONTEXT_SPEEDUP != 10.0:
        raise R27P3Error("full_context_speed_gate")
    if MIDPOINT_RECORD_BYTES != r20.MIDPOINT_RECORD_BYTES:
        raise R27P3Error("midpoint_record_bytes")

    required = (
        FULL_CONTEXT_ACCELERATOR_REQUIRED,
        EXACT_R20_OUTPUT_PARITY_REQUIRED,
        BOUNDS_PARITY_REQUIRED,
        FEATURE_SUMMARY_PARITY_REQUIRED,
        DECISION_ARRAY_PARITY_REQUIRED,
        BEST_BID_ARRAY_PARITY_REQUIRED,
        BEST_ASK_ARRAY_PARITY_REQUIRED,
        FEATURE_VALUES_PARITY_REQUIRED,
        MIDPOINT_RECORD_PARITY_REQUIRED,
        MIDPOINT_METADATA_PARITY_REQUIRED,
        RAW_EVENT_PASS_COUNT_PARITY_REQUIRED,
        ONE_CAUSAL_RAW_EVENT_PASS_REQUIRED,
        PYTHON_PER_ROW_LOOP_FORBIDDEN_IN_ACCELERATED_REAL_PATH,
        PYTHON_BOOK_OBJECT_MATERIALIZATION_PER_GROUP_FORBIDDEN,
        PYTHON_FULL_BOOK_SORT_PER_GROUP_FORBIDDEN,
        LOCAL_STREAM_SEMANTICS_FROZEN,
        EXCHANGE_STREAM_SEMANTICS_FROZEN,
        UNKNOWN_EVENT_FAIL_CLOSED,
        LOCAL_TIMESTAMP_REGRESSION_FAIL_CLOSED,
        EXCHANGE_TIMESTAMP_REGRESSION_FAIL_CLOSED,
        EVENT_SOURCE_ORDER_WITHIN_TIMESTAMP_GROUP_FROZEN,
        LOCAL_BOOK_BEFORE_SAME_TIMESTAMP_FLOWS_FROZEN,
        FINAL_TIMESTAMP_GROUP_FLUSH_REQUIRED,
        NATURAL_END_OF_SOURCE_SEMANTICS_FROZEN,
        ABSOLUTE_DEPTH_UPDATE_SEMANTICS_FROZEN,
        CLEAR_SEMANTICS_FROZEN,
        SNAPSHOT_SEMANTICS_FROZEN,
        TRADE_DOES_NOT_MUTATE_L2_FROZEN,
        IGNORED_L2_EVENT_POLICY_FROZEN,
        BBO_VALIDITY_RULE_FROZEN,
        TOP5_DEPTH_SEMANTICS_FROZEN,
        CANDIDATE_VISIBLE_QTY_SEMANTICS_FROZEN,
        ROLLING_WINDOWS_EXACT_TIMESTAMP_BASED,
        APPROXIMATE_SECOND_BUCKETING_FORBIDDEN,
        FEATURE_WARMUP_SEMANTICS_FROZEN,
        RECENT_BOOK_ASOF_250MS_FROZEN,
        RECENT_BOOK_ASOF_1S_FROZEN,
        ROLLING_1S_5S_30S_BOUNDARIES_FROZEN,
        FLOAT64_FEATURE_OUTPUT_REQUIRED,
        MIDPOINT_RECORD_DTYPE_FROZEN,
        MIDPOINT_EXCHANGE_TIMESTAMP_STRICTLY_INCREASING,
        MIDPOINT_LAST_BBO_PER_EXCHANGE_GROUP_FROZEN,
        MARKOUT_ASOF_RULE_FROZEN,
        INTERNAL_BOOK_REPRESENTATION_MAY_CHANGE,
        COMPILED_STATE_MACHINE_REQUIRED,
        BOUNDED_RING_BUFFERS_ALLOWED,
        TYPED_MAP_OR_VECTOR_BOOK_ALLOWED,
        DENSE_NUMPY_OUTPUT_SURFACE_REQUIRED,
        FILE_BACKED_MIDPOINT_OUTPUT_REQUIRED,
        SYNTHETIC_EXACT_PARITY_GATE_REQUIRED,
        BOUNDED_REAL_FULL_CONTEXT_PARITY_GATE_REQUIRED,
        BOUNDED_REAL_FULL_CONTEXT_SPEED_GATE_REQUIRED,
        FULL_JAN_JUL_RERUN_REQUIRES_SEPARATE_SUCCESSOR_AUTHORIZATION,
    )
    if not all(required):
        raise R27P3Error("required_guard")

    forbidden = (
        P2_ATTEMPT_CONSUMED,
        HISTORICAL_SOURCE_OPEN_AUTHORIZED,
        HISTORICAL_SOURCE_REHASH_AUTHORIZED,
        FULL_JAN_JUL_RERUN_AUTHORIZED,
        DURABLE_CONTEXT_WRITE_AUTHORIZED,
        SIMULATOR_LANE_AUTHORIZED,
        ATTEMPT_MARKER_WRITE_AUTHORIZED,
        CANONICAL_LABEL_WRITE_AUTHORIZED,
        MODEL_FIT_AUTHORIZED,
        PNL_AUTHORIZED,
        LIVE_TRADING_AUTHORIZED,
        AUG_OPEN_AUTHORIZED,
        SEP_PLUS_OPEN_AUTHORIZED,
        NON_BTC_OPEN_AUTHORIZED,
    )
    if any(forbidden):
        raise R27P3Error("execution_surface_open")


__all__ = [
    "ACCELERATOR_FAMILY",
    "DESIGN_VERSION",
    "EXPERIMENT_ID",
    "MIN_FULL_CONTEXT_SPEEDUP",
    "P2_ATTEMPT_CONSUMED",
    "R27P2_OBSERVED_GATE_SPEEDUP",
    "REFERENCE_IMPLEMENTATION",
    "validate_r27p3_contract",
]
