from __future__ import annotations

from pathlib import Path

from multimarket import dev045_d6r12_memory_attributed_real_diagnostic_contract as design


EXPERIMENT_ID = "DEV045-D6R12"
PREFLIGHT_ID = "DEV045-D6R12-REAL-DIAGNOSTIC-EXECUTION-PREFLIGHT-V1"
SCHEMA_VERSION = "dev045-d6r12-real-diagnostic-preflight-v1"
STAGE_MODE = "PREFLIGHT_AND_SYNTHETIC_EXECUTION_WRAPPER_ONLY"

PARENT_HEAD = "544dba4a2428e957049a46edb15d3558826f4ab7"
DESIGN_HEAD = "2aa65ad0cbfe3fdceaa4b76550ec14a35f25fe97"
DESIGN_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r12_memory_attributed_real_diagnostic_design_freeze.json"
)
DESIGN_FREEZE_MANIFEST_SHA256 = (
    "1f893eb9307bbc4ef52739a8674efeec97d10969ae3bc664e3de8c40092d3039"
)

D6R11_FREEZE_MANIFEST_PATH = Path(
    "evidence/dev045_d6r11_memory_attribution_freeze.json"
)
D6R11_FREEZE_MANIFEST_SHA256 = (
    "aa9128a7c0fbfbec94912a70bfbba21b04822fec9d94b837fa6179486ec03327"
)
D6R10_EVIDENCE_PATH = Path("evidence/dev045_d6r10_2026-02-01.json")
D6R10_EVIDENCE_SHA256 = (
    "83c648793d28c570fa1e1deee104eb6212464054786b95747f27bf3c88414c90"
)
D6R10_ATTEMPT_MARKER_PATH = Path(
    "/home/emadh/Multi-Market/runtime/dev045_d6r10/2026-02-01/ATTEMPT_STARTED.json"
)
D6R10_ATTEMPT_MARKER_SHA256 = (
    "9346106a92cb35f8681bfef7ba06b46ad719c9e55a93e833bd96ab68992b3ebb"
)
D6R10_HEARTBEAT_PATH = Path(
    "/home/emadh/Multi-Market/runtime/dev045_d6r10/2026-02-01/HEARTBEAT.json"
)
D6R10_HEARTBEAT_SHA256 = (
    "62ff826a0bc480cc321ce47b4dde57d9c8227968ede039c103aac94d8140cec3"
)

DAY = design.DAY
SYMBOL = design.SYMBOL
EXCHANGE = design.EXCHANGE
SOURCE_PATH = design.SOURCE_PATH
SOURCE_ROWS = design.SOURCE_ROWS
SOURCE_BYTES = design.SOURCE_BYTES
SOURCE_SHA256 = design.SOURCE_SHA256
SOURCE_LINEAGE_EVIDENCE_PATH = Path(
    "evidence/dev045_d6r9a_feb01_full_day_v2.json"
)
SOURCE_LINEAGE_EVIDENCE_SHA256 = (
    "54afd16ca610b76de0658d68764b661335fcda23e3ae3ca4ce4de93c57c199d9"
)

HFTBACKTEST_VERSION = "2.4.4"
BOUNDED_WAKEUP_TARGET = design.BOUNDED_WAKEUP_TARGET
WAKEUP_CAPTURE_INTERVAL = design.WAKEUP_CAPTURE_INTERVAL
PREEXEC_MIN_MEMAVAILABLE_BYTES = design.PREEXEC_MIN_MEMAVAILABLE_BYTES
RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES = (
    design.RUNTIME_MEMAVAILABLE_ABORT_THRESHOLD_BYTES
)
TOTAL_RSS_ABORT_THRESHOLD_BYTES = design.TOTAL_RSS_ABORT_THRESHOLD_BYTES
ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES = design.ANONYMOUS_RSS_ABORT_THRESHOLD_BYTES
RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH = (
    design.RUNTIME_ABORT_ON_PROCESS_SWAP_GROWTH
)
OLD_D6R10_ABORT_BYTES = design.OLD_D6R10_ABORT_BYTES
OLD_D6R10_LAST_HEARTBEAT_WAKEUPS = design.OLD_D6R10_LAST_HEARTBEAT_WAKEUPS
BOUNDED_TARGET_TERMINAL_REASON = design.BOUNDED_TARGET_TERMINAL_REASON
TARGET_OVERSHOOT_ERROR = design.TARGET_OVERSHOOT_ERROR
LIFECYCLE_CAPTURE_POINTS = design.LIFECYCLE_CAPTURE_POINTS
WAIT_NEXT_FEED_TIMEOUT_NS = 86_400_000_000_000

AUTHORIZATION_ENV = "DEV045_D6R12_AUTHORIZE"
AUTHORIZATION_TOKEN = "YES_FEB01_BOUNDED_MEMORY_DIAGNOSTIC"

# The authorization successor activates the independent execution lock. The
# exact environment token remains separately mandatory.
REAL_EXECUTION_ENABLED = True

RUNTIME_ROOT = Path("/home/emadh/Multi-Market/runtime/dev045_d6r12/2026-02-01")
ATTEMPT_MARKER_PATH = RUNTIME_ROOT / "ATTEMPT_STARTED.json"
MEMORY_HEARTBEAT_PATH = RUNTIME_ROOT / "MEMORY_HEARTBEAT.json"
EVIDENCE_PATH = Path("evidence/dev045_d6r12_2026-02-01.json")
D6R10_RUNTIME_ROOT = Path("/home/emadh/Multi-Market/runtime/dev045_d6r10")

MAX_SMALL_ARTIFACT_HASH_BYTES = 16 * 1024 * 1024
DIAGNOSTIC_TAIL_CHARS = 8192
TRACKED_WORKTREE_MUST_BE_CLEAN = True
INDEX_MUST_BE_CLEAN = True
SOURCE_PREFLIGHT_ACCESS = "STAT_ONLY"
SOURCE_CONTENT_HASH_DEFERRED_TO_AUTHORIZED_VERIFIED_MEMMAP_OPEN = True

MADV_SEQUENTIAL_IF_SUPPORTED = True
MEMMAP_OWNER_MUST_OUTLIVE_BACKTEST = True
BACKTEST_MUST_CLOSE_BEFORE_MEMMAP_CLOSE = True
SUCCESSOR_CLOSE_SEQUENCE = (
    "backtest_close",
    "capture_after_backtest_close",
    "memmap_close",
    "capture_after_memmap_close",
)

CANONICAL_DATA_OPEN_AUTHORIZED = False
HFTBACKTEST_CANONICAL_RUN_AUTHORIZED = False
ATTEMPT_MARKER_CREATION_AUTHORIZED = False
FULL_DAY_ATTEMPT_AUTHORIZED = False
FULL_DAY_VALIDATION_AUTHORIZED = False
MAR_TO_JUL_AUTHORIZED = False
POLICY_EXECUTION_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
ORDER_CANCEL_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
ECONOMIC_ARENA_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
RAW_CSV_OPEN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

PROHIBITED_EXECUTION_FLAGS = (
    CANONICAL_DATA_OPEN_AUTHORIZED,
    HFTBACKTEST_CANONICAL_RUN_AUTHORIZED,
    ATTEMPT_MARKER_CREATION_AUTHORIZED,
    FULL_DAY_ATTEMPT_AUTHORIZED,
    FULL_DAY_VALIDATION_AUTHORIZED,
    MAR_TO_JUL_AUTHORIZED,
    POLICY_EXECUTION_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    ORDER_CANCEL_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    ECONOMIC_ARENA_AUTHORIZED,
    CONVERTER_RERUN_AUTHORIZED,
    RAW_CSV_OPEN_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)

NEXT_STAGE = "DEV045-D6R12_REAL_DIAGNOSTIC_EXECUTION_CODE_FREEZE"
