from __future__ import annotations

from multimarket import (
    dev045_d6r26a_p2_r3_execution_authorization_contract as r3,
)
from multimarket import (
    dev045_d6r26a_p2_r20_combined_day_context_midpoint_index_preexecution as r20,
)
from multimarket import (
    dev045_d6r26a_p2_r22_final_successor_campaign_runner_binding_preauthorization as r22,
)
from multimarket import (
    dev045_d6r26a_p2_r23a_execution_head_lineage_amendment_preflight as r23a,
)

EXPERIMENT_ID = "DEV045-D6R26A-P2-R24"
DESIGN_VERSION = "durable-context-performance-preexecution-v1"

PARENT_R23A_HEAD = (
    "4e3e320931e896a6e479f3065eb60e118f993569"
)

P2_ATTEMPT_CONSUMED = False
HISTORICAL_SIMULATOR_LANE_STARTED = False

# Exact scientific semantics remain unchanged.
R20_CONTEXT_SEMANTICS_BOUND = True
R20_FEATURE_VALUES_MUST_BE_IDENTICAL = True
R20_MIDPOINT_VALUES_MUST_BE_IDENTICAL = True
R20_FEED_BOUNDS_MUST_BE_IDENTICAL = True
R20_DECISION_GRID_MUST_BE_IDENTICAL = True

SOURCE_REGISTRY_IDENTITY_MUST_BE_UNCHANGED = True
CANDIDATE_GRID_MUST_BE_UNCHANGED = True
ENGINE_IDENTITY_MUST_BE_UNCHANGED = True
LABEL_SEMANTICS_MUST_BE_UNCHANGED = True
SERIALIZER_CONTRACT_MUST_BE_UNCHANGED = True

# Durable architecture.
DURABLE_DAY_CONTEXT_REQUIRED = True
ALL_SEVEN_DURABLE_CONTEXTS_REQUIRED_BEFORE_ATTEMPT = True
DURABLE_CONTEXT_BUILD_DOES_NOT_CONSUME_SIMULATOR_ATTEMPT = True

COMPLETED_DAY_BUNDLE_REUSE_AFTER_REBOOT_AUTHORIZED = True
PARTIAL_DAY_BUNDLE_IS_NOT_COMPLETE = True
PARTIAL_DAY_BUNDLE_REUSE_FORBIDDEN = True

DURABLE_ROOT_NAME = "dev045_d6r26a_p2_durable_context_v1"

DAY_FILES = (
    "decision_local_ns.npy",
    "best_bid_tick.npy",
    "best_ask_tick.npy",
    "feature_values.npy",
    "exchange_midpoints.bin",
    "DAY_CONTEXT_MANIFEST.json",
)

ATOMIC_DAY_BUNDLE_PUBLISH_REQUIRED = True
STAGING_DIRECTORY_REQUIRED = True
DAY_MANIFEST_WRITTEN_LAST = True

DAY_SOURCE_IDENTITY_BOUND = True
DAY_SOURCE_SHA256_BOUND = True
DAY_FILE_BYTES_SHA256_BOUND = True
DAY_ARRAY_SHAPE_DTYPE_BOUND = True
DAY_R20_SUMMARY_BOUND = True

FINAL_RUNNER_MUST_VERIFY_ALL_SEVEN_DAY_BUNDLES = True
FINAL_RUNNER_RAW_CONTEXT_REBUILD_FORBIDDEN = True
FINAL_RUNNER_PARTIAL_BUNDLE_ACCEPTANCE_FORBIDDEN = True

# Full PC use, bounded by memory safety.
PARALLEL_DAY_CONTEXT_BUILD_AUTHORIZED = True
MAX_PARALLEL_DAY_CONTEXT_BUILD_CAP = 4
DYNAMIC_MEMORY_ADMISSION_REQUIRED = True
PREEXEC_MEMORY_POLICY_REMAINS_BOUND = True
RUNTIME_MEMORY_POLICY_REMAINS_BOUND = True

# Exact R3 attempt boundary remains unchanged.
ATTEMPT_CONSUMPTION_EVENT_UNCHANGED = True
FIRST_SIMULATOR_LANE_START_CONSUMES_ATTEMPT = True
RERUN_AFTER_ATTEMPT_MARKER_AUTHORIZED = False
RESUME_AFTER_ATTEMPT_MARKER_AUTHORIZED = False

PREEXECUTION_ONLY = True
THIS_COMMIT_OPENS_HISTORICAL_SOURCE = False
THIS_COMMIT_BUILDS_DURABLE_CONTEXT = False
THIS_COMMIT_RUNS_SIMULATOR = False
THIS_COMMIT_WRITES_CANONICAL_LABELS = False
THIS_COMMIT_WRITES_ATTEMPT_MARKER = False

MODEL_FIT_AUTHORIZED = False
MODEL_SELECTION_AUTHORIZED = False
THRESHOLD_TUNING_AUTHORIZED = False
PNL_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False


class R24ContractError(RuntimeError):
    pass


def validate_r24_contract() -> None:
    r3.validate_execution_authorization_contract()
    r22.validate_r22_contract()
    r23a.validate_r23a_contract()

    if PARENT_R23A_HEAD != (
        "4e3e320931e896a6e479f3065eb60e118f993569"
    ):
        raise R24ContractError("parent")

    if r20.MIDPOINT_RECORD_BYTES != 16:
        raise R24ContractError("midpoint_record_bytes")

    if r20.MIDPOINT_BUFFER_ROWS != 65_536:
        raise R24ContractError("midpoint_buffer_rows")

    if DAY_FILES[-1] != "DAY_CONTEXT_MANIFEST.json":
        raise R24ContractError("manifest_last")

    if MAX_PARALLEL_DAY_CONTEXT_BUILD_CAP != 4:
        raise R24ContractError("parallel_cap")

    required = (
        R20_CONTEXT_SEMANTICS_BOUND,
        R20_FEATURE_VALUES_MUST_BE_IDENTICAL,
        R20_MIDPOINT_VALUES_MUST_BE_IDENTICAL,
        R20_FEED_BOUNDS_MUST_BE_IDENTICAL,
        R20_DECISION_GRID_MUST_BE_IDENTICAL,
        SOURCE_REGISTRY_IDENTITY_MUST_BE_UNCHANGED,
        CANDIDATE_GRID_MUST_BE_UNCHANGED,
        ENGINE_IDENTITY_MUST_BE_UNCHANGED,
        LABEL_SEMANTICS_MUST_BE_UNCHANGED,
        SERIALIZER_CONTRACT_MUST_BE_UNCHANGED,
        DURABLE_DAY_CONTEXT_REQUIRED,
        ALL_SEVEN_DURABLE_CONTEXTS_REQUIRED_BEFORE_ATTEMPT,
        DURABLE_CONTEXT_BUILD_DOES_NOT_CONSUME_SIMULATOR_ATTEMPT,
        COMPLETED_DAY_BUNDLE_REUSE_AFTER_REBOOT_AUTHORIZED,
        PARTIAL_DAY_BUNDLE_IS_NOT_COMPLETE,
        PARTIAL_DAY_BUNDLE_REUSE_FORBIDDEN,
        ATOMIC_DAY_BUNDLE_PUBLISH_REQUIRED,
        STAGING_DIRECTORY_REQUIRED,
        DAY_MANIFEST_WRITTEN_LAST,
        DAY_SOURCE_IDENTITY_BOUND,
        DAY_SOURCE_SHA256_BOUND,
        DAY_FILE_BYTES_SHA256_BOUND,
        DAY_ARRAY_SHAPE_DTYPE_BOUND,
        DAY_R20_SUMMARY_BOUND,
        FINAL_RUNNER_MUST_VERIFY_ALL_SEVEN_DAY_BUNDLES,
        FINAL_RUNNER_RAW_CONTEXT_REBUILD_FORBIDDEN,
        FINAL_RUNNER_PARTIAL_BUNDLE_ACCEPTANCE_FORBIDDEN,
        PARALLEL_DAY_CONTEXT_BUILD_AUTHORIZED,
        DYNAMIC_MEMORY_ADMISSION_REQUIRED,
        PREEXEC_MEMORY_POLICY_REMAINS_BOUND,
        RUNTIME_MEMORY_POLICY_REMAINS_BOUND,
        ATTEMPT_CONSUMPTION_EVENT_UNCHANGED,
        FIRST_SIMULATOR_LANE_START_CONSUMES_ATTEMPT,
        PREEXECUTION_ONLY,
    )

    if not all(required):
        raise R24ContractError("required_guard")

    forbidden = (
        P2_ATTEMPT_CONSUMED,
        HISTORICAL_SIMULATOR_LANE_STARTED,
        RERUN_AFTER_ATTEMPT_MARKER_AUTHORIZED,
        RESUME_AFTER_ATTEMPT_MARKER_AUTHORIZED,
        THIS_COMMIT_OPENS_HISTORICAL_SOURCE,
        THIS_COMMIT_BUILDS_DURABLE_CONTEXT,
        THIS_COMMIT_RUNS_SIMULATOR,
        THIS_COMMIT_WRITES_CANONICAL_LABELS,
        THIS_COMMIT_WRITES_ATTEMPT_MARKER,
        MODEL_FIT_AUTHORIZED,
        MODEL_SELECTION_AUTHORIZED,
        THRESHOLD_TUNING_AUTHORIZED,
        PNL_AUTHORIZED,
        LIVE_TRADING_AUTHORIZED,
        AUG_OPEN_AUTHORIZED,
        SEP_PLUS_OPEN_AUTHORIZED,
        NON_BTC_OPEN_AUTHORIZED,
    )

    if any(forbidden):
        raise R24ContractError("closed_surface_open")


__all__ = [
    "EXPERIMENT_ID",
    "DESIGN_VERSION",
    "PARENT_R23A_HEAD",
    "DURABLE_ROOT_NAME",
    "DAY_FILES",
    "MAX_PARALLEL_DAY_CONTEXT_BUILD_CAP",
    "validate_r24_contract",
]
