from __future__ import annotations


EXPERIMENT_ID = "DEV045-D6R7A"
CONTRACT_ID = "DEV045-D6R7-CANONICAL-JAN-HFT-INGESTION-V1"
SCHEMA_VERSION = "dev045-d6r7-canonical-jan-hft-ingestion-contract-v1"


PARENT_BRANCH = (
    "research/dev045-m6-historical-driver-synthetic-memmap-binding"
)

PARENT_HEAD = (
    "56c46cd2f60e300a3a406d5ff81d9db068d2ecee"
)


D6R6B_IMPLEMENTATION_PATH = (
    "src/multimarket/dev045_d6r6_historical_driver.py"
)

D6R6B_IMPLEMENTATION_SHA256 = (
    "9463d99f9b32847ef14efd2c4d3d327205008bcae4715217b222037adfa4cff8"
)

D6R6B_TEST_SHA256 = (
    "3ca1ff3f5ae1570fa2facf1a1b200347fe408ba2cbbcd8c76701d3d848a154fc"
)

D6R6B_DOC_SHA256 = (
    "ddf06df80d2d733bd3e4bcf559e2f485a2a6f1935fb11eda7a673e9057ed609c"
)

D6R6B_WORKFLOW_SHA256 = (
    "a6d848589506bed6e0733c5d20beef36d6d94a16f35b1eec00f7e01f3cf463bd"
)

D6R6B_DEFAULT_CI_REQUIRED = "PASS"
D6R6B_PATCHED_HFT_CI_REQUIRED = "PASS"

D6R6B_DEFAULT_CI_RUN = 33_935_467_049
D6R6B_PATCHED_HFT_CI_RUN = 33_935_467_064


D6R5C_ARTIFACT_PATH = (
    "evidence/dev045_d6r5c_jan_memmap_validation.json"
)

D6R5C_ARTIFACT_SHA256 = (
    "79fa94de273c1ced6bf3a6a752331c8026056cbe5dabf22299f43b229cdeddf3"
)

D6R5C_STATUS = "PASS"

D6R5C_PEAK_RSS_BYTES = 4_221_472_768

MEMORY_SAFETY_MULTIPLIER = 2

REQUIRED_MEMAVAILABLE_BYTES = (
    D6R5C_PEAK_RSS_BYTES
    * MEMORY_SAFETY_MULTIPLIER
)

assert REQUIRED_MEMAVAILABLE_BYTES == 8_442_945_536

MEMORY_PROBE_SOURCE = "/proc/meminfo"
MEMORY_PROBE_FIELD = "MemAvailable"
SWAP_COUNTS_AS_AVAILABLE_MEMORY = False


EXCHANGE = "binance-futures"
SYMBOL = "BTCUSDT"
DAY = "2026-01-01"

CANONICAL_NPY_PATH = (
    "/home/emadh/Multi-Market/runtime/dev045_d6r4b/output/"
    "BTCUSDT_2026-01-01.npy"
)

CANONICAL_NPY_SHA256 = (
    "8f0a4fbd56ecdc261dbe2041ce138a09456423074925d495272716219a1d4da1"
)

CANONICAL_NPY_BYTES = 4_116_142_528
CANONICAL_NPY_ROWS = 64_314_723
CANONICAL_NPY_DEVICE_ID = 2096

EVENT_ITEMSIZE = 64

EVENT_FIELDS = (
    "ev",
    "exch_ts",
    "local_ts",
    "px",
    "qty",
    "order_id",
    "ival",
    "fval",
)


MEMMAP_ENTRYPOINT = (
    "multimarket.dev045_d6r5_memmap_adapter."
    "open_canonical_jan"
)

HFT_BINDING_ENTRYPOINT = (
    "multimarket.dev045_d6r6_historical_driver."
    "_build_lifetime_safe_binding"
)

HFTBACKTEST_VERSION = "2.4.4"

HFTBACKTEST_UPSTREAM_COMMIT = (
    "a244a14250b42d97fc305569c93c4117cd5e1dff"
)


PARALLEL_LOAD = False
FEED_LATENCY_OFFSET_NS = 0

FEED_PREPROCESSOR_AUTHORIZED = False
FEED_DATA_MUTATION_AUTHORIZED = False

SORT_OR_REORDER_AUTHORIZED = False
WHOLE_FILE_MATERIALIZATION_AUTHORIZED = False
ARRAY_COPY_OR_CONCATENATION_AUTHORIZED = False


INGESTION_MODE = "FEED_ONLY_NO_STRATEGY"

WAIT_NEXT_FEED_INCLUDE_ORDER_RESPONSE = False

WAIT_NEXT_FEED_TIMEOUT_NS = 86_400_000_000_000

EXPECTED_TERMINAL_RC = 1
MARKET_FEED_RC = 2

EXPECTED_POSITION = 0.0
EXPECTED_WORKING_ORDERS = 0

WAKEUP_COUNT_MUST_EQUAL_SOURCE_ROWS = False

TERMINAL_FEED_MAY_BE_APPLIED_BEFORE_END_OF_DATA_RC = True

WAKEUP_TIMESTAMPS_MUST_BE_NONDECREASING = True
AT_LEAST_ONE_MARKET_WAKEUP_REQUIRED = True

TERMINAL_BOOK_MUST_BE_VALID = True


RESOURCE_RECHECK_REQUIRED = True
RESOURCE_RECHECK_BEFORE_CANONICAL_ATTEMPT = True

SOURCE_IDENTITY_RECHECK_REQUIRED = True
SOURCE_IDENTITY_RECHECK_BEFORE_CANONICAL_ATTEMPT = True

SOURCE_FILE_MUST_BE_UNCHANGED_AFTER_RUN = True


CANONICAL_INGESTION_ATTEMPTS = 1

CANONICAL_ATTEMPT_STARTS_AT = (
    "_build_lifetime_safe_binding(source)"
)

FIRST_CANONICAL_INGESTION_RESULT_FROZEN = True
CANONICAL_RERUN_ALLOWED = False


MEMMAP_OWNER_MUST_OUTLIVE_BACKTEST = True
BACKTEST_CLOSE_BEFORE_MEMMAP_CLOSE = True


RESULT_EVIDENCE_PATH = (
    "evidence/dev045_d6r7b_canonical_jan_hft_ingestion.json"
)

RESULT_MUST_RECORD = (
    "STATUS",
    "CANONICAL_ATTEMPT",
    "MEMAVAILABLE_BYTES",
    "SOURCE_SHA256",
    "SOURCE_BYTES",
    "SOURCE_ROWS",
    "MARKET_WAKEUPS",
    "FIRST_MARKET_WAKEUP_NS",
    "LAST_MARKET_WAKEUP_NS",
    "TERMINAL_RC",
    "TERMINAL_TIMESTAMP_NS",
    "BEST_BID_TICK",
    "BEST_ASK_TICK",
    "POSITION",
    "WORKING_ORDER_COUNT",
    "PEAK_RSS_BYTES",
    "SOURCE_FILE_IDENTITY_BEFORE",
    "SOURCE_FILE_IDENTITY_AFTER",
    "LIFECYCLE",
)


PASS_REQUIRES = (
    "resource_precheck_pass",
    "exact_source_identity",
    "read_only_memmap",
    "hftbacktest_2_4_4",
    "canonical_binding_returned",
    "market_wakeup_seen",
    "monotonic_market_wakeup_timestamps",
    "terminal_rc_is_end_of_data",
    "terminal_book_valid",
    "position_zero",
    "working_orders_zero",
    "backtest_closed_before_memmap",
    "source_file_identity_unchanged",
)


D6R7A_OPENS_CANONICAL_JAN = False
D6R7A_RUNS_HFTBACKTEST = False

D6R7B_CANONICAL_JAN_OPEN_AUTHORIZED_AFTER_D6R7A_CI = True
D6R7B_HFTBACKTEST_INGESTION_AUTHORIZED_AFTER_D6R7A_CI = True

D6R7B_POLICY_EXECUTION_AUTHORIZED = False
D6R7B_ORDER_SUBMISSION_AUTHORIZED = False
D6R7B_ORDER_CANCEL_AUTHORIZED = False
D6R7B_PNL_AUTHORIZED = False


RAW_CSV_OPEN_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
CANONICAL_NPY_WRITE_AUTHORIZED = False

OTHER_DAY_OPEN_AUTHORIZED = False
FEB_TO_JUL_OPEN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False

HISTORICAL_POLICY_REPLAY_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
ECONOMIC_ARENA_AUTHORIZED = False
CANONICAL_PNL_WRITE_AUTHORIZED = False

NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False


NEXT_AFTER_D6R7A_CI = (
    "RUN_D6R7B_ONE_SHOT_CANONICAL_JAN_FEED_ONLY_HFT_INGESTION"
)
