from __future__ import annotations

EXPERIMENT_ID = "DEV045-D6R13"
SCHEMA_VERSION = "dev045-d6r13-child-launch-successor-design-v1"
STAGE_MODE = "DESIGN_AND_SYNTHETIC_SUBPROCESS_SMOKE_ONLY"

PARENT_D6R12_FAILURE_FREEZE_HEAD = "c20854aa9fec23ba6d7d0a665ab0f1e4458782d0"
D6R12_EXECUTION_HEAD = "4b70e7b303d677d3b4efebe904850b1df9274ac8"
D6R12_FAILURE_EVIDENCE_SHA256 = (
    "69c0cf784c39bcf75c7aea1a591ab10a808c8dd27855adb67d737f781226ccd1"
)
D6R12_FAILURE_FREEZE_MANIFEST_SHA256 = (
    "405fc0982f65d7982b5cf61939cf154bec65408aacdad9e548bebec629aa1c55"
)
D6R12_ATTEMPT_MARKER_SHA256 = (
    "ea7abf0ae8790555de056521514994e00a48c93e832e0670b6bad741bab82c19"
)

D6R12_FAILURE_CLASS = "CHILD_MODULE_RESOLUTION_FAILURE"
D6R12_RERUN_FORBIDDEN = True
DIAGNOSTIC_QUESTION_ANSWERED = False

CHILD_MODULE_NAME = "multimarket.dev045_d6r13_child_launch_successor"
SMOKE_PARENT_FLAG = "--smoke-parent"
SMOKE_CHILD_FLAG = "--child-launch-smoke"
REAL_CHILD_FLAG = "--child"

SMOKE_AUTH_ENV = "DEV045_D6R13_CHILD_LAUNCH_SMOKE"
SMOKE_AUTH_TOKEN = "YES_SYNTHETIC_MODULE_RESOLUTION_ONLY"

# D6R13 design must prove subprocess module resolution before any real successor
# execution code is introduced.
REAL_EXECUTION_ENABLED = False
CANONICAL_DATA_OPEN_AUTHORIZED = False
HFTBACKTEST_CANONICAL_RUN_AUTHORIZED = False
ATTEMPT_MARKER_CREATION_AUTHORIZED = False
HEARTBEAT_CREATION_AUTHORIZED = False
FULL_DAY_ATTEMPT_AUTHORIZED = False
POLICY_EXECUTION_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
CONVERTER_RERUN_AUTHORIZED = False
RAW_CSV_OPEN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

PROHIBITED_EXECUTION_FLAGS = (
    REAL_EXECUTION_ENABLED,
    CANONICAL_DATA_OPEN_AUTHORIZED,
    HFTBACKTEST_CANONICAL_RUN_AUTHORIZED,
    ATTEMPT_MARKER_CREATION_AUTHORIZED,
    HEARTBEAT_CREATION_AUTHORIZED,
    FULL_DAY_ATTEMPT_AUTHORIZED,
    POLICY_EXECUTION_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    CONVERTER_RERUN_AUTHORIZED,
    RAW_CSV_OPEN_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)

NEXT_STAGE = "DEV045-D6R13_CHILD_LAUNCH_SUCCESSOR_FREEZE"
