from __future__ import annotations


EXPERIMENT_ID = "DEV045-D6R11"
CONTRACT_ID = "DEV045-D6R11-MEMORY-ATTRIBUTION-SUCCESSOR-V1"
SCHEMA_VERSION = "dev045-d6r11-memory-attribution-v1"
MODE = "NON_CANONICAL_SYNTHETIC_MEMORY_ATTRIBUTION_ONLY"

PARENT_BRANCH = "research/dev045-m6-d6r10-feb01-failure-frozen"
PARENT_HEAD = "50663457ca3e12506160025ccd045bf9abeec197"
D6R10_EXECUTION_CODE_HEAD = "0f2129e1cc0f8b75377fb0fb01b01857b24ab18c"

D6R10_EVIDENCE_PATH = "evidence/dev045_d6r10_2026-02-01.json"
D6R10_EVIDENCE_SHA256 = (
    "83c648793d28c570fa1e1deee104eb6212464054786b95747f27bf3c88414c90"
)
D6R10_ATTEMPT_MARKER_SHA256 = (
    "9346106a92cb35f8681bfef7ba06b46ad719c9e55a93e833bd96ab68992b3ebb"
)
D6R10_HEARTBEAT_SHA256 = (
    "62ff826a0bc480cc321ce47b4dde57d9c8227968ede039c103aac94d8140cec3"
)
D6R10_STATUS = "FROZEN_FAIL"
D6R10_RERUN_AUTHORIZED = False

KIB_TO_BYTES = 1024

PROC_STATUS_PATH = "/proc/self/status"
PROC_MEMINFO_PATH = "/proc/meminfo"
PROC_SMAPS_ROLLUP_PATH = "/proc/self/smaps_rollup"
PROC_SMAPS_PATH = "/proc/self/smaps"

STATUS_FIELDS = (
    "VmRSS",
    "RssAnon",
    "RssFile",
    "RssShmem",
    "VmSize",
    "VmData",
    "VmSwap",
)
REQUIRED_STATUS_FIELDS = (
    "VmRSS",
    "RssAnon",
    "RssFile",
    "RssShmem",
)
OPTIONAL_STATUS_FIELDS = (
    "VmSize",
    "VmData",
    "VmSwap",
)

MEMINFO_FIELDS = ("MemAvailable",)
REQUIRED_MEMINFO_FIELDS = MEMINFO_FIELDS

SMAPS_ROLLUP_FIELDS = (
    "Rss",
    "Pss",
    "Pss_Anon",
    "Pss_File",
    "Private_Clean",
    "Private_Dirty",
    "Shared_Clean",
    "Shared_Dirty",
    "Anonymous",
    "Swap",
)
REQUIRED_SMAPS_ROLLUP_FIELDS = ("Rss", "Pss")

# This is a diagnostic relationship, not a resource gate. Linux exposes
# VmRSS as an approximate counter and documents it as the sum of the three
# resident classes below. D6R11 records any observed delta instead of choosing
# a tolerance or using the relationship to authorize execution.
RSS_DECOMPOSITION = "VmRSS - (RssAnon + RssFile + RssShmem)"
FILE_BACKED_RESIDENT_SOURCE = "RssFile"
ANONYMOUS_RESIDENT_SOURCE = "RssAnon"
SHARED_MEMORY_RESIDENT_SOURCE = "RssShmem"
TOTAL_RSS_SOURCE = "VmRSS"
SYSTEM_AVAILABLE_SOURCE = "MemAvailable"
CANONICAL_ABORT_THRESHOLD_BYTES = None

MEMMAP_OWNER_MUST_OUTLIVE_BACKTEST = True
BACKTEST_MUST_CLOSE_BEFORE_MEMMAP_CLOSE = True
FUTURE_MODE = "FEED_ONLY_NO_STRATEGY"

CANONICAL_DATA_OPEN_AUTHORIZED = False
CANONICAL_D6R11_EXECUTION_AUTHORIZED = False
HFTBACKTEST_EXECUTION_AUTHORIZED = False
HISTORICAL_POLICY_EXECUTION_AUTHORIZED = False
HISTORICAL_PNL_AUTHORIZED = False
ORDER_SUBMISSION_AUTHORIZED = False
ORDER_CANCEL_AUTHORIZED = False
RERUN_CONVERTER_AUTHORIZED = False
OPEN_RAW_CSV_AUTHORIZED = False
FEB_TO_JUL_OPEN_AUTHORIZED = False
AUG_OPEN_AUTHORIZED = False
SEP_PLUS_OPEN_AUTHORIZED = False
NON_BTC_OPEN_AUTHORIZED = False
NETWORK_ACQUISITION_AUTHORIZED = False
RAILWAY_AUTHORIZED = False
LIVE_TRADING_AUTHORIZED = False

PROHIBITED_EXECUTION_FLAGS = (
    CANONICAL_DATA_OPEN_AUTHORIZED,
    CANONICAL_D6R11_EXECUTION_AUTHORIZED,
    HFTBACKTEST_EXECUTION_AUTHORIZED,
    HISTORICAL_POLICY_EXECUTION_AUTHORIZED,
    HISTORICAL_PNL_AUTHORIZED,
    ORDER_SUBMISSION_AUTHORIZED,
    ORDER_CANCEL_AUTHORIZED,
    RERUN_CONVERTER_AUTHORIZED,
    OPEN_RAW_CSV_AUTHORIZED,
    FEB_TO_JUL_OPEN_AUTHORIZED,
    AUG_OPEN_AUTHORIZED,
    SEP_PLUS_OPEN_AUTHORIZED,
    NON_BTC_OPEN_AUTHORIZED,
    NETWORK_ACQUISITION_AUTHORIZED,
    RAILWAY_AUTHORIZED,
    LIVE_TRADING_AUTHORIZED,
)
